### ISSUE TITLE
Object.assign ES5 incompatibility

### ISSUE THREAD

**Issue by rafael-telles** [matheusportela/enigma-machine#5]
I saw you are using `Object.assign` on `test_enigma.js`, just be aware that this is a ES2015 feature and may not be compatible in some browsers or NodeJS versions.

More info: https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Browser_compatibility

**Comment by rafael-telles** [comment]
I noticed it by running your tests, I received these errors (because of my NodeJS version)

```
  1) Rotor Models Rotor I expect wiring table be correctly defined:
     TypeError: Object function Object() { [native code] } has no method 'assign'
      at assertWiringTable (test_enigma.js:234:39)
      at Context.<anonymous> (test_enigma.js:257:13)

  2) Rotor Models Rotor II expect wiring table be correctly defined:
     TypeError: Object function Object() { [native code] } has no method 'assign'
      at assertWiringTable (test_enigma.js:234:39)
      at Context.<anonymous> (test_enigma.js:267:13)

  3) Rotor Models Rotor III expect wiring table be correctly defined:
     TypeError: Object function Object() { [native code] } has no method 'assign'
      at assertWiringTable (test_enigma.js:234:39)
      at Context.<anonymous> (test_enigma.js:277:13)

  4) Rotor Models Rotor IV expect wiring table be correctly defined:
     TypeError: Object function Object() { [native code] } has no method 'assign'
      at assertWiringTable (test_enigma.js:234:39)
      at Context.<anonymous> (test_enigma.js:287:13)

  5) Rotor Models Rotor V expect wiring table be correctly defined:
     TypeError: Object function Object() { [native code] } has no method 'assign'
      at assertWiringTable (test_enigma.js:234:39)
      at Context.<anonymous> (test_enigma.js:297:13)

  6) Reflector Models Reflector B expect reflection table be correctly defined:
     TypeError: Object function Object() { [native code] } has no method 'assign'
      at assertReflectionTable (test_enigma.js:350:47)
      at Context.<anonymous> (test_enigma.js:365:13)

  7) Reflector Models Reflector C expect reflection table be correctly defined:
     TypeError: Object function Object() { [native code] } has no method 'assign'
      at assertReflectionTable (test_enigma.js:350:47)
      at Context.<anonymous> (test_enigma.js:372:13)

  8) Machine encode expect double stepping anomaly exists:
     TypeError: Object function Object() { [native code] } has no method 'assign'
      at Context.<anonymous> (test_enigma.js:468:44)
```

**Comment by matheusportela** [comment]
56378b42e2963060e1076becdd9a0301c1a23486 addresses this issue. Could you please test it for me?

**Comment by rafael-telles** [comment]
Surge I can! I will test it as soon I get my hands on a computer

**Comment by rafael-telles** [comment]
It worked!

**Comment by matheusportela** [comment]
Great, thanks!
